/// <reference types="knockout" />
declare class Safari {
    static grid: Array<Array<number>>;
    static pokemonGrid: KnockoutObservableArray<SafariPokemon>;
    static player: Point;
    static lastDirection: string;
    static nextDirection: string;
    static steps: number;
    static walking: boolean;
    static isMoving: boolean;
    static queue: Array<string>;
    private static playerXY;
    private static origin;
    static inProgress: KnockoutObservable<boolean>;
    static inBattle: KnockoutObservable<boolean>;
    static balls: KnockoutObservable<number>;
    static activeRegion: KnockoutObservable<GameConstants.Region>;
    static activeZone: KnockoutObservable<number>;
    static sizeX(): number;
    static sizeY(): number;
    static load(): void;
    private static addRandomBody;
    private static getRandomCoord;
    private static canAddBody;
    private static addBody;
    static safariReset(): void;
    static openModal(): void;
    static startSafari(): void;
    static closeModal(): void;
    private static canPay;
    private static cost;
    private static payEntranceFee;
    private static canAccess;
    static show(): void;
    private static square;
    private static addPlayer;
    static move(dir: string): void;
    private static startMoving;
    private static step;
    static spawnPokemonCheck(): void;
    static despawnPokemonCheck(): void;
    private static spawnRandomPokemon;
    private static directionToXY;
    private static canMove;
    private static setNextDirection;
    static stop(dir: string): void;
    private static checkBattle;
    private static calculateStartPokeballs;
    static completed(shiny?: boolean): boolean;
}
